apiVersion: v1
kind: Service
metadata:
  name: {{ include "alnoda-workspace.fullname" . }}
  labels:
    {{- include "alnoda-workspace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "alnoda-workspace.service-ports" . | nindent 4 }}
  selector:
    {{- include "alnoda-workspace.selectorLabels" . | nindent 4 }}
