# Default values for alnoda-workspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alnoda/alnoda-workspace
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: true
  className: ""
  annotations: {}
  host: example.local

resources: {}
  # limits:
  #   cpu: 2000m
  #   memory: 4000Mi
  # requests:
  #   cpu: 2000m
  #   memory: 4000Mi

nodeSelector: {}

tolerations: []

affinity: {}

customLabels: {}